/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import * as React from 'react';
import {
  StyleSheet,
  Text,
  View,
  ToastAndroid,
  NativeEventEmitter,
} from 'react-native';
import IdataScanner from 'react-native-idata-scanner';

interface Props {}
interface State {
  history: Array<string>;
}

export default class App extends React.Component<Props, State> {
  protected eventListener: any;

  constructor(props: Props) {
    super(props);
    this.state = {
      history: [],
    };
  }

  /**
   * 监听PDA扫码广播
   */
  registePdaEvent() {
    //设置扫码选项(当PDA设备能通过广播进行设置的时候可用)
    const rows = [{key: 'barcode_send_mode', value: 'BROADCAST'}];
    IdataScanner.setBroadcastSetting(
      'com.android.scanner.service_settings',
      rows,
    );

    //广播和接收字段(接收的广播名和接收的字段名)
    IdataScanner.getCode('android.intent.action.SCANRESULT', 'value');

    if (this.eventListener) {
      this.eventListener.remove();
    }

    const eventEmitter = new NativeEventEmitter();
    this.eventListener = eventEmitter.addListener(
      'scannerCodeShow',
      ({code}) => {
        this.setState({history: [].concat(code, this.state.history)});

        ToastAndroid.show(`code: ${code}`, ToastAndroid.SHORT);
      },
    );
  }

  render() {
    const {history} = this.state;
    console.log(history);

    return (
      <View style={styles.container}>
        <View style={{height: 50}}>
          <Text style={styles.welcome}>IdataScanner Example</Text>
        </View>

        <View style={{flex: 1, overflow: 'hidden'}}>
          {history.map((code, idx) => (
            <Text
              key={idx}
              style={{
                borderBottomWidth: 1,
                borderBottomColor: 'rgba(0,0,0,0.1)',
                borderStyle: 'dashed',
                padding: 5,
              }}>
              {code}
            </Text>
          ))}
        </View>

        <View style={{height: 50}}>
          <Text style={styles.instructions}>
            please press device button for scan
          </Text>
        </View>
      </View>
    );
  }

  componentDidMount() {
    // IdataScanner.sampleMethod('Testing', 123, (message) => {
    //   this.setState({
    //     status: 'native callback received',
    //     message
    //   });
    // });

    this.registePdaEvent();
  }

  componentWillUnmount() {
    if (this.eventListener) {
      this.eventListener.remove(); // 组件卸载时记得移除监听事件
    }
  }
}

const styles = StyleSheet.create({
  container: {
    display: 'flex',
    height: '100%',
    padding: 15,
  },
  welcome: {
    fontSize: 18,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    justifyContent: 'center',
  },
});
